### ISSUE TITLE
Switcam HS-303 - additional option to turn on the IR backlight

### ISSUE THREAD

**Issue by ZigFisher** [OpenIPC/majestic_issues#10]
In the majestic config.yaml there is no possibility to specify the GPIO to enable IR illumination

Example of manual activation and deactivation IR light from the console:

```
echo 1 >/sys/class/gpio/gpio65/value
```

```
echo 0 >/sys/class/gpio/gpio65/value
```

Also please see /usr/sbin/ircut sctipt and calling it from a file /etc/crontabs/root

**Comment by widgetii** [comment]
Added `backlightPin` in night stanza

Please test against latest build and close the issue if everything is ok

**Comment by ZigFisher** [comment]
The new version works fine, man !
Thank you very much. The ticket can be closed.
