### ISSUE TITLE
Switcam HS-303 - IR filter is controlled by a single gpio64

### ISSUE THREAD

**Issue by ZigFisher** [OpenIPC/majestic_issues#11]
* Camera board id: Rostelecom Switcam HS-303
 * OpenIPC version: v1.0 OpenWrt based
 * Commit: 8328d61
 * Branch: master

There is also no way to specify in the config that the IR filter is controlled by a single gpio64

Example of manual activation and deactivation IR filter from the console:

```
echo 1 >/sys/class/gpio/gpio64/value
```

```
echo 0 >/sys/class/gpio/gpio64/value
```

Also please see /usr/sbin/ircut sctipt and calling it from a file /etc/crontabs/root

**Comment by widgetii** [comment]
If only irCutPin1 is provided app will use the single GPIO mode described above.

Please test against latest build and close the issue if everything is ok

**Comment by ZigFisher** [comment]
The new version works fine, man !
Thank you very much. The ticket can be closed.
