### ISSUE TITLE
switcam-hs303 Проблема с записью видео на SD карту

### ISSUE THREAD

**Issue by Storoj1** [OpenIPC/majestic_issues#13]
Добрый день.
# Required information
1. switcam-hs303. s/n 090000030832
2. OpenIPC.org for Switcam HS303 v1 | 2021.01.24
3.  installation method: (by manual https://github.com/OpenIPC/openipc-2.1/wiki/install_hisi 
4. Файл majestic.yaml модифицирован. 
[лог терминала.txt](https://github.com/OpenIPC/majestic_issues/files/6814597/default.txt)
[содержание конф файла.txt](https://github.com/OpenIPC/majestic_issues/files/6814598/default.txt)

Использую вашу прошивку в камере switcam-hs303.
# Issue description
Столкнулся с проблемой - отсутствие записи на SD карту.
#Steps to reproduce
1. Поправил конфиг файл : majestic.yaml . Изменил false  на  true в параметре records:
  enabled: true
  path: /sdcard/%Y/%m/%d/%H.mp4/
# Expectations
Запись видео на sd карту
# Результат 
В логах пишет - daemon.info majestic: 10:12:02 ERROR [storage] save_mp4_to_storage@232: mp4: cannot write
Пробовал разные SD карты. Прилагаю Лог файл и Конфиг.
[лог терминала.txt](https://github.com/OpenIPC/majestic_issues/files/6814440/default.txt)
[содержание конф файла.txt](https://github.com/OpenIPC/majestic_issues/files/6814442/default.txt)

**Comment by widgetii** [comment]
Присутствует ли в файловой системе каталог `/sdcard`? Смонтирована ли SD карта в него?

**Comment by Storoj1** [comment]
Каталог /sdcard присутствует. В каталоге /mnt присутствует файл /mmc. В каталоге /dev нет привычных   "sda"  "hda".
В логе терминала есть информация о карте и определении ее размера. Попытка создать файл в каталоге /sdcard  закончилась неудачей. Система сказала , что не может создать файл. Может есть какие нибудь требования по форматированию карты и объему ? p.s.  Я не знаю как проверить смонтирована карта или нет. Примеры для вариантов линукс не подходят. Результат проверяю вытаскивая  sd
карту и проверяя его на стационарном компьютере

**Comment by widgetii** [comment]
В данном случае это не проблема стримера, а настроек операционной системы
Вы можете попросить помощи в [русскоязычном Telegram канале](https://t.me/openipc_modding)

**Comment by Storoj1** [comment]
Продолжение истории. Я взял новую карту и отформатировал её в exFAT  В каталоге /sdcard пр работе камеры появляется папка 2021. Так же в том же каталоге /sdcard стало возможным создать файл типа test.txt При выключении камеры и проверки карты памяти  в картридере на  ПК - опять на ней ничего нет. Соответственно вопрос. В какой каталог при применении доступа через терминал к камере должны записываться файлы видео ?  И ещё один вопрос, как в терминале перейти из режима консоли , в режим отображения текущего лога?

**Comment by ZigFisher** [comment]
```
records:             
  enabled: true 
  path: /mnt/mmc/%Y/%m/%d/%H.mp4                           
                                                   
  # in %           
  maxUsage: 95

```
