### ISSUE TITLE
hi3516ev300 

### ISSUE THREAD

**Issue by zWolf-SW** [OpenIPC/majestic_issues#14]
# Required information

 * Camera board id: hi3516ev300 
 * OpenIPC version: 2.1
 * Commit:
 * Branch:
 * Tag:
 * installation method: (by manual https://github.com/OpenIPC/openipc-2.1/wiki/install_hisi or another)
 * modified majestic.yaml: yes
 * cat /dev/kmsg
 * killall majestic
   ulimit -c unlimited
   echo /tmp/%e.%p.%s.%t.core > /proc/sys/kernel/core_pattern
   majestic
   Core dump file from /tmp/ , e.g. /tmp/majestic.806.11.1619707881.core

# Issue description

1. Не работает mirror - при включении в majestic.yaml вообще нет видеопотока
2. Не работает ipeye при отсутствии соединения eth0 (соединение wifi установлено) при старте majestic ошибка: IPEYE: Unable generate TID, при установленном соединении eth0 все нормально, наличие физического соединения eth0 без доступа в сеть проблему не решает.

# Expectations

# Steps to reproduce

 1. Step one
 2. Step two
 3. Step three

# Information to attach

 - [ ] Any relevant log output (`logread -f`)
 - [ ] majestic.yaml configuration (`cat /etc/majestic.yaml`)

**Comment by zWolf-SW** [comment]
[majestic.log](https://github.com/OpenIPC/majestic_issues/files/7075509/majestic.log)

**Comment by zWolf-SW** [comment]
[ifconfig.txt](https://github.com/OpenIPC/majestic_issues/files/7075670/ifconfig.txt)

**Comment by zWolf-SW** [comment]
[majestic.yaml.txt](https://github.com/OpenIPC/majestic_issues/files/7076011/majestic.yaml.txt)

**Comment by zWolf-SW** [comment]
[dev_kmsg.txt](https://github.com/OpenIPC/majestic_issues/files/7076071/dev_kmsg.txt)

**Comment by zWolf-SW** [comment]
[dev_kmsg.txt](https://github.com/OpenIPC/majestic_issues/files/7076140/dev_kmsg.txt)

**Comment by ZigFisher** [comment]
По пункту 2 предлагаю внести в конфиг имя интерфейса, по которому будет генерироваться TID, т.к. постепенно появляются камеры с WiFi, а скоро будут даже такие, у которых eth0 интерфейс отсутствует полностью..

**Comment by widgetii** [comment]
Please test against the latest build for Ipeye issue

**Comment by zWolf-SW** [comment]
TID генерируется, все ОК  
11:49:12 [   ipeye] ipeye_open_session@93         IPEYE new client
11:49:12 [   ipeye] ipeye_send_handshake@43       Connected to IPEYE network as 40:d6:3c:34:d5:c0

**Comment by zWolf-SW** [comment]
примечание, нужно еще раскомментировать codec: h264  в majestic.yaml иначе на сайте картинки нет...
