### ISSUE TITLE
hi3516ev300 mirror

### ISSUE THREAD

**Issue by zWolf-SW** [OpenIPC/majestic_issues#16]
[majestic.log](https://github.com/OpenIPC/majestic_issues/files/7115347/majestic.log)
# Required information

 * Camera board id: hi3516ev300
 * OpenIPC version: 2.1
 * Commit:  2021-09-02

 * Branch:
 * Tag:
 * installation method: manual
 * modified majestic.yaml: yes
 * cat /dev/kmsg
 * killall majestic
   ulimit -c unlimited
   echo /tmp/%e.%p.%s.%t.core > /proc/sys/kernel/core_pattern
   majestic
   Core dump file from /tmp/ , e.g. /tmp/majestic.806.11.1619707881.core

# Issue description
при включении mirror в majestic.yaml картинки нет.

A brief description of the problem. Should include what you were
attempting to do, what you did, what happened and what you expected to
see happen.

# Expectations

# Steps to reproduce

 1. Step one
 2. Step two
 3. Step three

# Information to attach

 - [ ] Any relevant log output (`logread -f`)
 - [ ] majestic.yaml configuration (`cat /etc/majestic.yaml`)
[majestic.log.txt](https://github.com/OpenIPC/majestic_issues/files/7115356/majestic.log.txt)
[majestic.yaml.txt](https://github.com/OpenIPC/majestic_issues/files/7115358/majestic.yaml.txt)
[dmesg.txt](https://github.com/OpenIPC/majestic_issues/files/7115361/dmesg.txt)

**Comment by widgetii** [comment]
EV300 family doesn't support mirror mode due to ViPipe capacity. You might want to rewrite sensor driver for specific hardware and use the built-in sensor's mirror mode that was implemented in the original firmware but we have no plans to support such functionally in tree free version.
