### ISSUE TITLE
mjpeg поток розовый, при этом 0 и 1 потоки правильные

### ISSUE THREAD

**Issue by vebmaster** [OpenIPC/majestic_issues#22]
Здравствуйте.

3516ev200 imx307
master+b924f45, 2021-10-17

mjpeg поток розовый, при этом 0 и 1 потоки правильные

мой конфиг - [majestic.yaml.txt](https://github.com/OpenIPC/majestic_issues/files/7364766/majestic.yaml.txt)

**Comment by ZigFisher** [comment]
Проверьте пожалуйста сборку завтра (соберётся ночью) и отпишитесь здесь и если работает - закройте тикет.

У меня на 18ev200 всё заработало адекватно.

**Comment by vebmaster** [comment]
> Проверьте пожалуйста сборку завтра

master+8931ae1, 2021-12-20
Спасибо большое Игорь. Теперь mjpeg поток правильный.
