### ISSUE TITLE
[Feature request] add possibility to change sensor max gain in auto exposure mode

### ISSUE THREAD

**Issue by HugasRadvilenas** [OpenIPC/majestic_issues#29]
is it possible to add possibility to change maximal gain in auto mode ?

R.

**Comment by widgetii** [comment]
In the latest build when `exposure: auto` all three settings `aGain`, `dGain`, `ispGain` act as maximum gain in auto mode

Please test and give a feedback

**Comment by HugasRadvilenas** [comment]
have tried ispGain: 0.1 , ispGain: 0.5 ,  ispGain: 1 ,but ISPDGainRange.Max in pqtool is always shown as 4096 ...
so looks like not working - or i'm entering wrong values ?

**Comment by widgetii** [comment]
Please check the latest build, it turns out some code wasn't merged properly.

In auto mode every value applied to ISP as is without multiplicators, so for `ISPDGainRange.Max` == 4096 you need to set `ispGain: 4096`

**Comment by HugasRadvilenas** [comment]
Works now ! Have set ispGain to 1024 ant it chanhed as expected . Good job & thank you !
