### ISSUE TITLE
Different color palette when working in night mode

### ISSUE THREAD

**Issue by ZigFisher** [OpenIPC/majestic_issues#31]
### HI3518EV200 + OV9732 = HS303v2

Different color palette when working in night mode.
The jpeg and hls channels look adequate in night mode, and the mjpeg channel glows pink (there is an idea that some kind of software filter does not work)

**Comment by widgetii** [comment]
Please check the latest build. It turns out that the system didn't take into account the current night mode state while MJPEG channel created

**Comment by ZigFisher** [comment]
Fixed, many thanks ! ;)
