### ISSUE TITLE
Build Time Information

### ISSUE THREAD

**Issue by ZigFisher** [OpenIPC/majestic_issues#4]
Please add to the --version command the output of information about the build time of the program, as done in the logo header at startup. At the moment, the output of the version contains code only for machines, but not for people.
Thanks !

```
root@ipcam:~# majestic --version
master+0fdae09
```

`Majestic version master+0fdae09, built on 2021-05-11`

**Comment by widgetii** [comment]
Implemented in today build:

```
root@ipcam:~# majestic --version
master+f8d20f4, 2021-06-10
```

**Comment by ZigFisher** [comment]
Thanks !
