### ISSUE TITLE
osd posX and posY does not work

### ISSUE THREAD

**Issue by darkbyte-ru** [OpenIPC/majestic_issues#6]
Changing osd posX and posY does not affect on label position, I tried different positive and negative values.

majestic version: master+37ff773, 2021-06-17

**Comment by widgetii** [comment]
It seems the bug appeared when we made the transition to yamlStyle naming in config
Please check the latest build, issue has been resolved on my camera

**Comment by darkbyte-ru** [comment]
Yep, works normal in master+5e05922, 2021-06-20
