### ISSUE TITLE
 Switcam HS-303 - the camera freezes if turn night mode

### ISSUE THREAD

**Issue by ZigFisher** [OpenIPC/majestic_issues#9]
* Camera board id: Rostelecom Switcam HS-303
 * OpenIPC version: v1.0 OpenWrt based
 * Commit: 8328d61
 * Branch: master

The camera freezes if you turn on automatic night mode on majestic and assign gpio62 for lighting detect

**Comment by widgetii** [comment]
Please provide /etc/majestic.yaml

**Comment by widgetii** [comment]
It seems I found the root the cause: we never tested new GPIO pin muxing code before

Fixed
